# Generated by Django 6.0.6 on 2026-08-02 21:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(allow_unicode=True, help_text='Внутренний ключ. У встроенных видов постоянный, у своих — из названия.', max_length=40, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('block', models.CharField(choices=[('MATERIALS', 'Материалы'), ('FIXED', 'Постоянные расходы'), ('VARIABLE', 'Переменные расходы')], max_length=12, verbose_name='блок отчёта')),
                ('in_profit', models.BooleanField(default=True, help_text='Снято — расход виден в отчёте, но прибыль не уменьшает (как покупка оборудования).', verbose_name='входит в прибыль')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='встроенный')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='порядок в блоке')),
                ('is_archived', models.BooleanField(default=False, verbose_name='скрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'вид расхода',
                'verbose_name_plural': 'виды расходов',
                'ordering': ['block', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_start', models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — считается по складу автоматически.', max_digits=14, null=True, verbose_name='остаток материалов на начало')),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Фикс. сумма за каждого приведённого клиента. Только показывается в карточке клиента — в расходы автоматически НЕ списывается.', max_digits=14, verbose_name='бонус за приведённого клиента')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки финотчёта',
                'verbose_name_plural': 'настройки финотчёта',
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='за что / кому')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='сумма')),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.expensekind', verbose_name='вид расхода')),
            ],
            options={
                'verbose_name': 'расход',
                'verbose_name_plural': 'расходы',
                'ordering': ['-spent_at', '-created_at'],
                'indexes': [models.Index(fields=['kind', 'spent_at'], name='finance_exp_kind_id_67910a_idx')],
            },
        ),
    ]
