# Generated by Django 4.2.30 on 2026-06-27 12:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_start', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='остаток материалов на начало')),
                ('material_purchase', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='закуп материала')),
                ('transport', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='транспортные расходы')),
                ('material_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='долг материала')),
                ('rent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='аренда цеха')),
                ('utilities', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='коммунальные услуги')),
                ('internet', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='интернет')),
                ('fixed_other', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='прочие постоянные расходы')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки финотчёта',
                'verbose_name_plural': 'настройки финотчёта',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CUTTER', 'Расходники фреза'), ('EQUIPMENT', 'Покупка оборудования'), ('IMPROVEMENT', 'Улучшение цеха'), ('OTHER', 'Прочие расходы')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='название')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='сумма')),
                ('spent_at', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'расход/инвестиция',
                'verbose_name_plural': 'расходы/инвестиции',
                'ordering': ['-spent_at', '-created_at'],
            },
        ),
    ]
