# Generated by Django 4.2.30 on 2026-07-01 17:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='fixed_other_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='что входит в прочие'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='зарплаты за месяц'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='utilities_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='что входит в коммуналку'),
        ),
    ]
