# Generated by Django 6.0.6 on 2026-07-14 05:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financesettings_fixed_other_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Фикс. сумма за каждого приведённого клиента. Только показывается в карточке клиента — в расходы автоматически НЕ списывается.', max_digits=14, verbose_name='бонус за приведённого клиента'),
        ),
    ]
