# Generated by Django 6.0.6 on 2026-08-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_builtin_expense_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Как в документах: ОсОО «...» или ИП Фамилия И.О.', max_length=255, verbose_name='название организации')),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='телефон')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='банк')),
                ('bank_account', models.CharField(blank=True, max_length=64, verbose_name='расчётный счёт')),
                ('bik', models.CharField(blank=True, max_length=32, verbose_name='БИК')),
                ('director', models.CharField(blank=True, help_text='ФИО для строки подписи', max_length=255, verbose_name='руководитель')),
                ('accountant', models.CharField(blank=True, max_length=255, verbose_name='бухгалтер')),
                ('note', models.CharField(blank=True, help_text='Например «НДС не облагается» или срок оплаты счёта', max_length=255, verbose_name='примечание в документах')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'реквизиты организации',
                'verbose_name_plural': 'реквизиты организации',
            },
        ),
    ]
