# Generated by Django 6.0.6 on 2026-08-16 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_companyprofile'),
        ('sales', '0005_receipt_change_due'),
        ('warehouse', '0005_supplier_supply_inventorylog_supply_supplyline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('CASH', 'Наличные'), ('BANK', 'Банк')], default='CASH', max_length=10, verbose_name='счёт')),
                ('kind', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')], max_length=10, verbose_name='тип')),
                ('article', models.CharField(choices=[('SALE', 'Оплата от клиента'), ('CHANGE', 'Сдача клиенту'), ('REFUND', 'Возврат клиенту'), ('UNPAY', 'Откат оплаты'), ('SUPPLY', 'Оплата поставщику'), ('EXPENSE', 'Расход цеха'), ('SALARY', 'Зарплата'), ('TRANSFER', 'Инкассация / перевод'), ('DEPOSIT', 'Внесение денег'), ('COUNT', 'Пересчёт кассы'), ('OTHER', 'Прочее')], default='OTHER', max_length=20, verbose_name='статья')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('happened_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('is_auto', models.BooleanField(default=False, verbose_name='создана системой')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to='sales.receipt', verbose_name='чек')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='warehouse.supply', verbose_name='накладная')),
            ],
            options={
                'verbose_name': 'кассовая операция',
                'verbose_name_plural': 'кассовая книга',
                'ordering': ['-happened_on', '-created_at'],
                'indexes': [models.Index(fields=['account', 'happened_on'], name='finance_cas_account_d4390a_idx')],
            },
        ),
    ]
