# Generated by Django 6.0.6 on 2026-08-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fixed_expenses_and_salaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('CUTTER', 'Расходники фреза'), ('TRANSPORT', 'Транспортные расходы'), ('EQUIPMENT', 'Покупка оборудования'), ('IMPROVEMENT', 'Улучшение цеха'), ('OTHER', 'Прочие расходы')], max_length=20),
        ),
    ]
