# Generated by Django 6.0.6 on 2026-08-16 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cashentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_through', models.DateField(blank=True, help_text='Эта дата и всё, что раньше — только на чтение. Пусто — период открыт', null=True, verbose_name='закрыто по')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'закрытие периода',
                'verbose_name_plural': 'закрытие периода',
            },
        ),
    ]
