# Generated by Django 6.0.6 on 2026-09-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_supplier_payment'),
        ('sales', '0012_returned_at_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='sales.receipt', verbose_name='чек'),
        ),
    ]
