# Generated by Django 6.0.6 on 2026-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_cashentry_receipt_keep_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='article',
            field=models.CharField(choices=[('SALE', 'Оплата от клиента'), ('CHANGE', 'Сдача клиенту'), ('REFUND', 'Возврат клиенту'), ('UNPAY', 'Откат оплаты'), ('SUPPLY', 'Оплата поставщику'), ('EXPENSE', 'Расход цеха'), ('SALARY', 'Зарплата'), ('TRANSFER', 'Инкассация / перевод'), ('DEPOSIT', 'Вложение владельца'), ('OWNER_OUT', 'Изъятие владельцем'), ('LOAN_IN', 'Займ получен'), ('LOAN_OUT', 'Займ погашен'), ('COUNT', 'Пересчёт кассы'), ('OTHER', 'Прочее')], default='OTHER', max_length=20, verbose_name='статья'),
        ),
    ]
