# Generated by Django 6.0.6 on 2026-10-10 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_cash_opening_and_lot_keeps_payment'),
        ('sales', '0015_idempotency_item_lots_indexes'),
        ('warehouse', '0015_inventorylog_receipt_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['happened_on'], name='cash_happened_on_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['spent_at'], name='expense_spent_at_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['period'], name='expense_period_idx'),
        ),
    ]
