# Generated by Django 6.0.9 on 2026-10-10 12:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee'),
        ('finance', '0017_builtin_kinds_bad_debt_warranty_fx'),
        ('warehouse', '0016_inventorylog_roll_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='сверено с выпиской'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='когда сверено'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='finance.expenseentry', verbose_name='актив'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='is_cashless',
            field=models.BooleanField(default=False, help_text='Начисление или карточка актива: в кассу не пишется.', verbose_name='без денег'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='master_share_in_margin',
            field=models.BooleanField(default=False, help_text='Отчёты маржи по услугам вычтут долю мастера из маржи. В ОПиУ не влияет.', verbose_name='учитывать долю мастера в марже строки'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='payroll_prev_month_until_day',
            field=models.PositiveSmallIntegerField(default=31, help_text='Выплата зарплаты до этого числа по умолчанию — за прошлый месяц. 0 — всегда за текущий.', validators=[django.core.validators.MaxValueValidator(31)], verbose_name='расчёт за прошлый месяц — до числа'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='basis',
            field=models.CharField(choices=[('ACCRUAL', 'По начислению (от выручки)'), ('CASH', 'По кассе (от полученных денег)')], default='ACCRUAL', max_length=10, verbose_name='основа налога'),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='article',
            field=models.CharField(choices=[('SALE', 'Оплата от клиента'), ('CHANGE', 'Сдача клиенту'), ('REFUND', 'Возврат клиенту'), ('UNPAY', 'Откат оплаты'), ('SUPPLY', 'Оплата поставщику'), ('EXPENSE', 'Расход цеха'), ('SALARY', 'Зарплата'), ('TRANSFER', 'Инкассация / перевод'), ('DEPOSIT', 'Вложение владельца'), ('OWNER_OUT', 'Изъятие владельцем'), ('LOAN_IN', 'Займ получен'), ('LOAN_OUT', 'Займ погашен'), ('COUNT', 'Пересчёт кассы'), ('OPENING', 'Ввод начального остатка'), ('PAYROLL', 'Выплата зарплаты по ведомости'), ('OTHER', 'Прочее')], default='OTHER', max_length=20, verbose_name='статья'),
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='за месяц')),
                ('reason', models.CharField(choices=[('DEFECT', 'За брак'), ('FINE', 'Штраф'), ('OTHER', 'Прочее удержание')], default='FINE', max_length=10, verbose_name='причина')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='сумма')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='accounts.employee', verbose_name='сотрудник')),
                ('inventory_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments', to='warehouse.inventorylog', verbose_name='списание')),
            ],
            options={
                'verbose_name': 'удержание',
                'verbose_name_plural': 'удержания',
                'ordering': ['-month', 'employee_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='действует с месяца')),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='оклад в месяц')),
                ('bonus_metric', models.CharField(choices=[('RUNNING_METERS', 'Погонные метры резки'), ('WORK_AMOUNT', 'Сумма выполненных работ, сом')], default='RUNNING_METERS', max_length=20, verbose_name='чем мерится выработка для премии')),
                ('bonus_threshold', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Выработка за месяц СТРОГО больше порога — премия. Пусто — без премии.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='порог выработки для премии')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='премия')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_schemes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_schemes', to='accounts.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'правила оплаты',
                'verbose_name_plural': 'правила оплаты',
                'ordering': ['employee_id', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(choices=[('CUTTING', 'Резка (любой станок)'), ('CUTTING_CNC', 'Резка на ЧПУ'), ('CUTTING_LASER', 'Резка на лазере'), ('ENGRAVING', 'Гравировка'), ('INSTALL', 'Монтаж и установка'), ('OTHER', 'Прочие работы')], max_length=20, verbose_name='вид работы')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='процент от стоимости работы')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.payscheme')),
            ],
            options={
                'verbose_name': 'процент от работы',
                'verbose_name_plural': 'проценты от работы',
                'ordering': ['scheme_id', 'work'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='за что / кому')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('account', models.CharField(choices=[('CASH', 'Наличные'), ('BANK', 'Банк')], default='CASH', max_length=10, verbose_name='чем заплатили')),
                ('day', models.PositiveSmallIntegerField(default=1, help_text='В коротком месяце — последний день.', verbose_name='число месяца')),
                ('start_month', models.DateField(verbose_name='с месяца')),
                ('until_month', models.DateField(blank=True, null=True, verbose_name='по месяц включительно')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring', to='finance.expensekind', verbose_name='вид расхода')),
            ],
            options={
                'verbose_name': 'повторяющаяся трата',
                'verbose_name_plural': 'повторяющиеся траты',
                'ordering': ['-is_active', 'kind__block', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.recurringexpense', verbose_name='повторяющаяся трата'),
        ),
        migrations.CreateModel(
            name='PayrollAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='за месяц')),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='начислено')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='удержано')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='к оплате за месяц')),
                ('breakdown', models.JSONField(blank=True, default=dict, verbose_name='расчёт')),
                ('posted_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_accruals', to='accounts.employee', verbose_name='сотрудник')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accrual', to='finance.expenseentry', verbose_name='расход в ОПиУ')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accruals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'начисление зарплаты',
                'verbose_name_plural': 'начисления зарплаты',
                'ordering': ['-month', 'employee_id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'month'), name='payrollaccrual_employee_month_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='за какой месяц')),
                ('kind', models.CharField(choices=[('ADVANCE', 'Аванс'), ('PAYOUT', 'Выплата')], default='PAYOUT', max_length=10, verbose_name='вид')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='сумма')),
                ('paid_on', models.DateField(verbose_name='дата выплаты')),
                ('account', models.CharField(choices=[('CASH', 'Наличные'), ('BANK', 'Банк')], default='CASH', max_length=10, verbose_name='чем заплатили')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payment', to='finance.cashentry', verbose_name='запись кассы')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='accounts.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'выплата зарплаты',
                'verbose_name_plural': 'выплаты зарплаты',
                'ordering': ['-paid_on', '-created_at'],
                'indexes': [models.Index(fields=['period'], name='payrollpay_period_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payscheme',
            constraint=models.UniqueConstraint(fields=('employee', 'valid_from'), name='payscheme_employee_from_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payrate',
            constraint=models.UniqueConstraint(fields=('scheme', 'work'), name='payrate_scheme_work_uniq'),
        ),
    ]
