# Generated by Django 6.0.9 on 2026-10-11 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee'),
        ('finance', '0019_archive_warranty_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payscheme',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_schemes', to='accounts.employee', verbose_name='сотрудник'),
        ),
    ]
