# Generated by Django 4.2.30 on 2026-06-05 18:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('category', models.CharField(db_index=True, max_length=120, verbose_name='категория')),
                ('category_ru', models.CharField(db_index=True, max_length=120, null=True, verbose_name='категория')),
                ('category_ky', models.CharField(db_index=True, max_length=120, null=True, verbose_name='категория')),
                ('category_en', models.CharField(db_index=True, max_length=120, null=True, verbose_name='категория')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='остаток')),
                ('critical_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Лимит, ниже которого срабатывает алерт', max_digits=12, verbose_name='критический остаток')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='закупочная цена за единицу')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена продажи клиенту, напр. 50 сом за 1 метр', max_digits=12, verbose_name='розничная цена за единицу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materials/', verbose_name='изображение')),
                ('is_primary', models.BooleanField(default=False, verbose_name='главное фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouse.material')),
            ],
            options={
                'verbose_name': 'фото материала',
                'verbose_name_plural': 'фото материалов',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUPPLY', 'Поступление'), ('ADJUSTMENT', 'Корректировка/Инвентаризация')], max_length=20)),
                ('quantity_changed', models.DecimalField(decimal_places=2, help_text='Положительное — приход, отрицательное — списание', max_digits=12, verbose_name='изменение количества')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='новая цена закупки')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='warehouse.material')),
            ],
            options={
                'verbose_name': 'складская операция',
                'verbose_name_plural': 'складские операции',
                'ordering': ['-created_at'],
            },
        ),
    ]
