# Generated by Django 6.0.6 on 2026-08-02 21:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='толщина, мм')),
                ('color', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='цвет')),
                ('article', models.CharField(blank=True, help_text='Код цвета поставщика, напр. 237', max_length=40, verbose_name='артикул')),
                ('sheet_width', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='ширина листа, м')),
                ('sheet_height', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='высота листа, м')),
                ('unit', models.CharField(choices=[('SQM', 'кв.м'), ('METER', 'пог.м'), ('PIECE', 'шт'), ('KG', 'кг'), ('LITER', 'л')], default='PIECE', max_length=10, verbose_name='единица измерения')),
                ('is_roll_material', models.BooleanField(default=False, help_text='Приходит рулонами, продаётся по кв.м, списывается из партий', verbose_name='рулонный материал')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='остаток')),
                ('critical_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Лимит, ниже которого срабатывает алерт', max_digits=12, verbose_name='критический остаток')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='закупочная цена за единицу')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена продажи клиенту, напр. 50 сом за 1 метр', max_digits=12, verbose_name='розничная цена за единицу')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена продажи по площади / вырезки, сом за 1 кв.м', max_digits=12, verbose_name='цена за кв.м')),
                ('piece_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Фикс. цена за целую штуку. 0 — продажа штукой недоступна', max_digits=12, verbose_name='цена за штуку (лист/рулон)')),
                ('piece_area', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Считается из размера листа; вводится вручную только без размера', max_digits=12, verbose_name='площадь листа, кв.м')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена за лист при продаже от опт. минимума. 0 — опта нет', max_digits=12, verbose_name='оптовая цена за лист')),
                ('wholesale_min_qty', models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='С какого количества листов включается оптовая цена', max_digits=12, verbose_name='опт от, листов')),
                ('cut_rate_per_pm', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Стоимость работы резки за погонный метр для этого материала', max_digits=12, verbose_name='ставка резки, сом/пог.м')),
                ('is_archived', models.BooleanField(default=False, verbose_name='скрыт из каталога')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(allow_unicode=True, help_text='Внутренний ключ. У встроенных постоянный, у своих — из названия.', max_length=40, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='встроенный')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('is_archived', models.BooleanField(default=False, verbose_name='скрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'тип материала',
                'verbose_name_plural': 'типы материалов',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(allow_unicode=True, max_length=40, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='встроенное')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('is_archived', models.BooleanField(default=False, verbose_name='скрыто')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'производство',
                'verbose_name_plural': 'производства',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUPPLY', 'Поступление'), ('SALE', 'Продажа'), ('RETURN', 'Возврат от клиента'), ('ADJUSTMENT', 'Корректировка/Инвентаризация'), ('WRITE_OFF', 'Списание (порча/брак/утеря)')], max_length=20)),
                ('quantity_changed', models.DecimalField(decimal_places=4, help_text='Положительное — приход, отрицательное — списание', max_digits=14, verbose_name='изменение количества')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='новая цена закупки')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='причина')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата операции')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='sales.receipt', verbose_name='чек')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='warehouse.material')),
            ],
            options={
                'verbose_name': 'складская операция',
                'verbose_name_plural': 'складские операции',
                'ordering': ['-happened_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materials/', verbose_name='изображение')),
                ('is_primary', models.BooleanField(default=False, verbose_name='главное фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouse.material')),
            ],
            options={
                'verbose_name': 'фото материала',
                'verbose_name_plural': 'фото материалов',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='warehouse.materialtype', verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='material',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='warehouse.productionsite', verbose_name='производство'),
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=120, verbose_name='маркировка партии')),
                ('form', models.CharField(choices=[('ROLL', 'Рулон'), ('SHEET', 'Лист')], default='ROLL', max_length=10)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sheet_count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('initial_area', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='площадь при поступлении, кв.м')),
                ('remaining_area', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='остаток, кв.м')),
                ('purchase_cost', models.DecimalField(decimal_places=2, help_text='Полная стоимость закупки рулона', max_digits=12, verbose_name='себестоимость рулона')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата поступления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='warehouse.material')),
            ],
            options={
                'verbose_name': 'рулон',
                'verbose_name_plural': 'рулоны',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialMonthOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='месяц')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='остаток на начало месяца')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_openings', to='warehouse.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_openings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'остаток на начало месяца',
                'verbose_name_plural': 'остатки на начало месяца',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('material', 'year', 'month'), name='unique_material_month_opening')],
            },
        ),
    ]
