# Generated by Django 4.2.30 on 2026-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='type',
            field=models.CharField(choices=[('SUPPLY', 'Поступление'), ('ADJUSTMENT', 'Корректировка/Инвентаризация'), ('WRITE_OFF', 'Списание (порча/брак/утеря)')], max_length=20),
        ),
    ]
