# Generated by Django 4.2.30 on 2026-06-08 12:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_alter_inventorylog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_roll_material',
            field=models.BooleanField(default=False, help_text='Приходит рулонами, продаётся по кв.м, списывается из партий', verbose_name='рулонный материал'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('SQM', 'кв.м'), ('METER', 'пог.м'), ('PIECE', 'шт'), ('KG', 'кг'), ('LITER', 'л')], default='PIECE', max_length=10, verbose_name='единица измерения'),
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=120, verbose_name='маркировка рулона')),
                ('initial_area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='площадь при поступлении, кв.м')),
                ('remaining_area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='остаток, кв.м')),
                ('purchase_cost', models.DecimalField(decimal_places=2, help_text='Полная стоимость закупки рулона', max_digits=12, verbose_name='себестоимость рулона')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=6, verbose_name='наценка, %')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='warehouse.material')),
            ],
            options={
                'verbose_name': 'рулон',
                'verbose_name_plural': 'рулоны',
                'ordering': ['received_at'],
            },
        ),
    ]
