# Generated by Django 6.0.6 on 2026-08-14 04:43

from django.db import migrations, models


def form_from_last_lot(apps, schema_editor):
    """Уже заведённым материалам форму берём из их последней партии.

    До этой правки форму («рулон» или «лист») выбирали в каждом поступлении, и
    у материала она нигде не хранилась. Ставить всем «лист» по умолчанию —
    значит переучивать складовщика там, где система и так знает ответ: чем
    материал приходил в прошлый раз, тем почти наверняка придёт и в следующий.
    """
    Material = apps.get_model("warehouse", "Material")
    Roll = apps.get_model("warehouse", "Roll")
    for material in Material.objects.filter(is_roll_material=True):
        last = Roll.objects.filter(material=material).order_by("-received_at").first()
        if last and last.form == "ROLL":
            Material.objects.filter(pk=material.pk).update(intake_form="ROLL")


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_builtin_production_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='intake_form',
            field=models.CharField(blank=True, choices=[('SHEET', 'Лист'), ('ROLL', 'Рулон')], default='SHEET', help_text='Лист или рулон. Только для материалов по кв.м', max_length=10, verbose_name='форма поступления'),
        ),
        migrations.RunPython(form_from_last_lot, migrations.RunPython.noop),
    ]
