# Generated by Django 4.2.30 on 2026-06-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_material_is_roll_material_material_unit_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='form',
            field=models.CharField(choices=[('ROLL', 'Рулон'), ('SHEET', 'Лист')], default='ROLL', max_length=10),
        ),
        migrations.AddField(
            model_name='roll',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='sheet_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='code',
            field=models.CharField(blank=True, max_length=120, verbose_name='маркировка партии'),
        ),
    ]
