# Generated by Django 6.0.6 on 2026-08-14 14:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_material_intake_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='название')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='телефон')),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('is_archived', models.BooleanField(default=False, verbose_name='скрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Номер бумажной накладной поставщика', max_length=64, verbose_name='номер накладной')),
                ('received_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата накладной')),
                ('stated_total', models.DecimalField(blank=True, decimal_places=2, help_text='Как в бумаге. Пусто — сверять не с чем', max_digits=14, null=True, verbose_name='сумма по накладной')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='оплачено поставщику')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='warehouse.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'приходная накладная',
                'verbose_name_plural': 'приходные накладные',
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='warehouse.supply', verbose_name='накладная'),
        ),
        migrations.CreateModel(
            name='SupplyLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('SHEET', 'Лист'), ('ROLL', 'Рулон'), ('QTY', 'По количеству')], default='SHEET', max_length=10)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sheet_count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='принято')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма строки')),
                ('code', models.CharField(blank=True, max_length=120, verbose_name='маркировка партии')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_lines', to='warehouse.material')),
                ('roll', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_line', to='warehouse.roll')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.supply')),
            ],
            options={
                'verbose_name': 'строка накладной',
                'verbose_name_plural': 'строки накладной',
                'ordering': ['id'],
            },
        ),
    ]
