# Generated by Django 4.2.30 on 2026-06-19 14:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_roll_form_roll_height_roll_length_roll_sheet_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='piece_area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Площадь одного листа/рулона — списывается при продаже «целиком»', max_digits=12, verbose_name='площадь штуки, кв.м'),
        ),
        migrations.AddField(
            model_name='material',
            name='piece_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Фикс. цена за целую штуку. 0 — продажа штукой недоступна', max_digits=12, verbose_name='цена за штуку (лист/рулон)'),
        ),
        migrations.AddField(
            model_name='material',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена продажи по площади / вырезки, сом за 1 кв.м', max_digits=12, verbose_name='цена за кв.м'),
        ),
    ]
