# Generated by Django 6.0.6 on 2026-08-18 03:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_supplier_supply_inventorylog_supply_supplyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price_per_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='цена продажи, сом/пог.м'),
        ),
        migrations.AddField(
            model_name='material',
            name='roll_width',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Для рулонного материала: постоянная ширина полотна', max_digits=8, null=True, verbose_name='ширина рулона, м'),
        ),
    ]
