# Generated by Django 4.2.30 on 2026-06-19 15:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_material_piece_area_material_piece_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cut_rate_per_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Стоимость работы резки за погонный метр для этого материала', max_digits=12, verbose_name='ставка резки, сом/пог.м'),
        ),
    ]
