# Generated by Django 4.2.30 on 2026-06-27 14:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_material_cut_rate_per_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='wholesale_min_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='С какого количества листов включается оптовая цена', max_digits=12, verbose_name='опт от, листов'),
        ),
        migrations.AddField(
            model_name='material',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена за лист при продаже от опт. минимума. 0 — опта нет', max_digits=12, verbose_name='оптовая цена за лист'),
        ),
    ]
