# Generated by Django 6.0.6 on 2026-08-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_material_price_per_pm_material_roll_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='declared_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='заявлено поставщиком, м'),
        ),
        migrations.AlterField(
            model_name='material',
            name='roll_width',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Подставляется в приёмку. Фактическая ширина замораживается в партии', max_digits=8, null=True, verbose_name='ширина рулона, м'),
        ),
    ]
