# Generated by Django 6.0.6 on 2026-08-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_material_wholesale_min_qty_material_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='скрыт из каталога'),
        ),
    ]
