# Generated by Django 6.0.6 on 2026-08-18 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_roll_declared_length_alter_material_roll_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RollStocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_metres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='было по системе, м')),
                ('counted_metres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='намерено по факту, м')),
                ('difference', models.DecimalField(decimal_places=2, help_text='Минус — недостача, плюс — излишек', max_digits=12, verbose_name='расхождение, м')),
                ('reason_code', models.CharField(choices=[('SUPPLIER', 'Недомер при приёмке'), ('CUTTING', 'Потери при резке'), ('DAMAGE', 'Порча'), ('MISCOUNT', 'Ошибка учёта'), ('OTHER', 'Прочее')], default='OTHER', max_length=20, verbose_name='причина')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_stocktakes', to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='warehouse.roll', verbose_name='рулон')),
            ],
            options={
                'verbose_name': 'акт промера рулона',
                'verbose_name_plural': 'акты промера рулонов',
                'ordering': ['-created_at'],
            },
        ),
    ]
