# Generated by Django 6.0.6 on 2026-08-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_rollstocktake'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='metres_changed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='изменение в пог.м'),
        ),
    ]
