# Generated by Django 6.0.6 on 2026-08-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_add_archive_and_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='production',
            field=models.CharField(blank=True, help_text='Откуда возят: напр. Бишкек, Глобал', max_length=120, verbose_name='производство'),
        ),
    ]
