# Generated by Django 6.0.6 on 2026-08-02 10:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_material_production'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMonthOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='месяц')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='остаток на начало месяца')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_openings', to='warehouse.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_openings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'остаток на начало месяца',
                'verbose_name_plural': 'остатки на начало месяца',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('material', 'year', 'month'), name='unique_material_month_opening')],
            },
        ),
    ]
