# Generated by Django 6.0.6 on 2026-08-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_inventorylog_metres_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='warehouse.productionsite', verbose_name='производство'),
        ),
    ]
