# Generated by Django 6.0.6 on 2026-08-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_roll_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='form',
            field=models.CharField(choices=[('ROLL', 'Рулон'), ('SHEET', 'Лист'), ('PIECE', 'Штучный')], default='ROLL', max_length=10),
        ),
    ]
