# Generated by Django 6.0.6 on 2026-09-27 05:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_supplier_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='supplier_debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='долг поставщику'),
        ),
    ]
