# Generated by Django 6.0.6 on 2026-10-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_idempotency_item_lots_indexes'),
        ('warehouse', '0014_roll_supplier_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='receipt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='sales.transactionitem', verbose_name='строка чека'),
        ),
    ]
