# Generated by Django 6.0.9 on 2026-10-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_inventorylog_receipt_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='warehouse.roll', verbose_name='партия'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='type',
            field=models.CharField(choices=[('SUPPLY', 'Поступление'), ('SALE', 'Продажа'), ('RETURN', 'Возврат от клиента'), ('ADJUSTMENT', 'Корректировка/Инвентаризация'), ('WRITE_OFF', 'Списание (порча/брак/утеря)'), ('CORRECTION', 'Исправление прихода')], max_length=20),
        ),
    ]
