# Поставщики и накладные (волна 1 аудита 10.10): платежи отдельными строками,
# возвраты, начальные остатки и долги, валюта закупа. Только новые таблицы и
# поля с умолчанием; данные не переносятся и прошлые цифры не меняются.
# Generated by Django 6.0.9 on 2026-10-10 12:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_report_date_indexes'),
        ('warehouse', '0016_inventorylog_roll_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='currency',
            field=models.CharField(default='KGS', max_length=3, verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='supply',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name='начальные остатки'),
        ),
        migrations.AddField(
            model_name='supply',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14, verbose_name='курс, сом за единицу валюты'),
        ),
        migrations.AddField(
            model_name='supplyline',
            name='cost_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='сумма строки в валюте'),
        ),
        migrations.CreateModel(
            name='SupplierOpeningDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(default=django.utils.timezone.localdate, verbose_name='на дату')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма, сом')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_opening_debts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_debts', to='warehouse.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'начальный долг поставщику',
                'verbose_name_plural': 'начальные долги поставщикам',
                'ordering': ['as_of', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAYMENT', 'Оплата'), ('REFUND', 'Возврат денег от поставщика'), ('OFFSET', 'Зачёт аванса')], default='PAYMENT', max_length=10)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата')),
                ('account', models.CharField(blank=True, choices=[('CASH', 'Наличные'), ('BANK', 'Банк')], max_length=10, verbose_name='счёт')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма, сом')),
                ('fx_diff', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='курсовая разница, сом')),
                ('currency', models.CharField(default='KGS', max_length=3, verbose_name='валюта')),
                ('amount_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='сумма в валюте')),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='курс на дату оплаты')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='finance.cashentry', verbose_name='запись кассы')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('fx_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='finance.expenseentry', verbose_name='курсовая разница')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offsets', to='warehouse.supplierpayment', verbose_name='аванс')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='warehouse.supplier', verbose_name='поставщик')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='warehouse.supply', verbose_name='накладная')),
            ],
            options={
                'verbose_name': 'платёж поставщику',
                'verbose_name_plural': 'платежи поставщикам',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата возврата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='стоимость возвращённого, сом')),
                ('refund', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='возвращено деньгами, сом')),
                ('refund_account', models.CharField(blank=True, max_length=10)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_returns', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='warehouse.supplier', verbose_name='поставщик')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='warehouse.supply', verbose_name='накладная')),
            ],
            options={
                'verbose_name': 'возврат поставщику',
                'verbose_name_plural': 'возвраты поставщикам',
                'ordering': ['-returned_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=160)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='возвращено, в единицах строки')),
                ('area', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='возвращено, кв.м или шт')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='стоимость, сом')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_lines', to='warehouse.material')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.supplierreturn')),
                ('supply_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_lines', to='warehouse.supplyline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
