# Generated by Django 6.0.9 on 2026-10-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_supplier_ledger_returns_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена-подсказка = закуп последней партии × (1 + наценка)', max_digits=7, null=True, verbose_name='наценка, %'),
        ),
    ]
