# Generated by Django 6.0.9 on 2026-10-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_material_markup_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='kim_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Списание куска = площадь деталей ÷ КИМ; целые листы — как есть', max_digits=5, null=True, verbose_name='КИМ раскроя, %'),
        ),
    ]
