# Generated by Django 6.0.9 on 2026-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_material_kim_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='min_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Листы, метры или штуки. «К заказу» — до двух минимумов', max_digits=12, null=True, verbose_name='минимальный остаток, в единицах материала'),
        ),
    ]
