# Generated by Django 6.0.9 on 2026-10-10 15:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_material_min_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stored_rolls', to='warehouse.productionsite', verbose_name='площадка хранения'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='type',
            field=models.CharField(choices=[('SUPPLY', 'Поступление'), ('SALE', 'Продажа'), ('RETURN', 'Возврат от клиента'), ('ADJUSTMENT', 'Корректировка/Инвентаризация'), ('WRITE_OFF', 'Списание (порча/брак/утеря)'), ('CORRECTION', 'Исправление прихода'), ('TRANSFER', 'Перемещение')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='перемещено, кв.м (шт)')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='по закупу')),
                ('happened_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouse.productionsite', verbose_name='откуда')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='warehouse.material')),
                ('to_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouse.productionsite', verbose_name='куда')),
            ],
            options={
                'verbose_name': 'перемещение',
                'verbose_name_plural': 'перемещения',
                'ordering': ['-happened_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LotPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кв.м (шт)')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='warehouse.roll')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_placements', to='warehouse.productionsite', verbose_name='площадка')),
            ],
            options={
                'verbose_name': 'часть партии на площадке',
                'verbose_name_plural': 'части партий на площадках',
                'constraints': [models.UniqueConstraint(fields=('roll', 'site'), name='lot_placement_roll_site')],
            },
        ),
    ]
