# Generated by Django 6.0.9 on 2026-10-10 15:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_stock_sites_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(unique=True, verbose_name='на конец дня')),
                ('source', models.CharField(default='command', max_length=20, verbose_name='откуда')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='стоимость склада')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'снимок склада',
                'verbose_name_plural': 'снимки склада',
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='остаток, кв.м (шт)')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='по закупу')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_lines', to='warehouse.material')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_lines', to='warehouse.roll')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.stocksnapshot')),
            ],
            options={
                'verbose_name': 'строка снимка склада',
                'verbose_name_plural': 'строки снимка склада',
            },
        ),
    ]
