# Generated by Django 6.0.9 on 2026-10-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_stock_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='от, листов')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена за лист')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='warehouse.material')),
            ],
            options={
                'verbose_name': 'ступень опта',
                'verbose_name_plural': 'ступени опта',
                'ordering': ['material', 'min_qty'],
                'constraints': [models.UniqueConstraint(fields=('material', 'min_qty'), name='price_tier_material_min_qty')],
            },
        ),
    ]
