# Generated by Django 6.0.9 on 2026-10-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_material_price_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierreturn',
            name='amount_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='стоимость возвращённого в валюте'),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='in_place',
            field=models.BooleanField(default=True, verbose_name='накладная правится на месте'),
        ),
        migrations.AddField(
            model_name='supplierreturnline',
            name='cost_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='стоимость в валюте'),
        ),
        migrations.CreateModel(
            name='InventoryLogLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='кв.м (шт), со знаком')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_moves', to='warehouse.inventorylog')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_moves', to='warehouse.roll')),
            ],
            options={
                'verbose_name': 'партия движения склада',
                'verbose_name_plural': 'партии движений склада',
            },
        ),
    ]
