# Generated by Django 6.0.9 on 2026-10-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_backfill_sale_lot_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='reorder_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — до двух минимумов', max_digits=12, null=True, verbose_name='заказывать до, в единицах материала'),
        ),
    ]
