# Generated by Django 6.0.9 on 2026-10-11 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_transactionitem_ordering'),
        ('warehouse', '0026_material_reorder_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leftover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(choices=[('SQM', 'кв.м (ширина × длина)'), ('METER', 'пог.м'), ('PIECE', 'штуки')], max_length=10, verbose_name='мерка')),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='ширина куска, м')),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='длина куска, м')),
                ('pieces', models.PositiveIntegerField(verbose_name='положено кусков')),
                ('pieces_left', models.PositiveIntegerField(verbose_name='на полке кусков')),
                ('written_off_pieces', models.PositiveIntegerField(default=0, verbose_name='списано кусков')),
                ('status', models.CharField(choices=[('ON_SHELF', 'На полке'), ('PARTIAL', 'Продан частично'), ('SOLD', 'Продан'), ('WRITTEN_OFF', 'Списан')], db_index=True, default='ON_SHELF', max_length=12, verbose_name='статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='положили')),
                ('written_off_at', models.DateTimeField(blank=True, null=True, verbose_name='списан')),
                ('write_off_reason', models.CharField(blank=True, max_length=255, verbose_name='причина списания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftovers_put', to=settings.AUTH_USER_MODEL, verbose_name='положил')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leftovers', to='warehouse.material', verbose_name='материал')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leftovers', to='warehouse.productionsite', verbose_name='площадка хранения')),
                ('source_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftovers', to='sales.receipt', verbose_name='заказ-источник')),
                ('written_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftovers_written_off', to=settings.AUTH_USER_MODEL, verbose_name='списал')),
            ],
            options={
                'verbose_name': 'остаток на полке',
                'verbose_name_plural': 'полка остатков',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
