# Generated by Django 4.2.30 on 2026-06-05 18:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Резка букв', max_length=255, verbose_name='название')),
                ('name_ru', models.CharField(default='Резка букв', max_length=255, null=True, verbose_name='название')),
                ('name_ky', models.CharField(default='Резка букв', max_length=255, null=True, verbose_name='название')),
                ('name_en', models.CharField(default='Резка букв', max_length=255, null=True, verbose_name='название')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='базовая стоимость')),
                ('paper_markup', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='наценка за обычную бумагу, %')),
                ('cardboard_markup', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='наценка за картон, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_per_unit', models.DecimalField(decimal_places=3, help_text='Напр. 1.1 метра бумаги на 1 метр резки', max_digits=12, verbose_name='норма расхода на 1 ед. услуги')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='warehouse.material')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='services.printingservice')),
            ],
            options={
                'verbose_name': 'норма расхода',
                'verbose_name_plural': 'технологическая карта',
                'unique_together': {('service', 'material')},
            },
        ),
    ]
