# Generated by Django 6.0.6 on 2026-08-02 21:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('4'), help_text='Доля мастера от стоимости работы резки (видна только админу)', max_digits=5, verbose_name='ЗП мастера, % от работы')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки ценообразования',
                'verbose_name_plural': 'настройки ценообразования',
            },
        ),
        migrations.CreateModel(
            name='PrintingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Резка букв', max_length=255, verbose_name='название')),
                ('name_ru', models.CharField(default='Резка букв', max_length=255, null=True, verbose_name='название')),
                ('name_ky', models.CharField(default='Резка букв', max_length=255, null=True, verbose_name='название')),
                ('name_en', models.CharField(default='Резка букв', max_length=255, null=True, verbose_name='название')),
                ('kind', models.CharField(choices=[('CUTTING', 'Резка / работа мастера (по кв.м)'), ('INSTALL_EXTERIOR', 'Наружная установка (за букву)'), ('INSTALL_INTERIOR', 'Внутренняя установка (по кв.м)'), ('INSTALLATION', 'Установка (фикс)'), ('OTHER', 'Прочее (фикс)')], default='CUTTING', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Для установки/прочего — фикс. цена за заказ', max_digits=12, verbose_name='фиксированная стоимость')),
                ('rate_flat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ставка работы за кв.м')),
                ('rate_per_piece', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ставка за букву')),
                ('paper_markup', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('cardboard_markup', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_per_unit', models.DecimalField(decimal_places=3, help_text='На кв.м: расход на 1 кв.м; Фикс: расход на заказ', max_digits=12, verbose_name='норма расхода')),
                ('applies_to', models.CharField(choices=[('ALL', 'Всегда')], default='ALL', max_length=20)),
                ('consumption_mode', models.CharField(choices=[('PER_SQM', 'На кв.м'), ('FIXED', 'Фикс. на заказ')], default='PER_SQM', max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='warehouse.material')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='services.printingservice')),
            ],
            options={
                'verbose_name': 'норма расхода',
                'verbose_name_plural': 'технологическая карта',
                'unique_together': {('service', 'material', 'applies_to')},
            },
        ),
    ]
