# Generated by Django 4.2.30 on 2026-06-08 12:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_roll_form_roll_height_roll_length_roll_sheet_count_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicerecipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='printingservice',
            name='kind',
            field=models.CharField(choices=[('CUTTING', 'Резка (по кв.м)'), ('INSTALLATION', 'Установка (фикс)'), ('OTHER', 'Прочее (фикс)')], default='CUTTING', max_length=20),
        ),
        migrations.AddField(
            model_name='printingservice',
            name='rate_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ставка за кв.м (плоские)'),
        ),
        migrations.AddField(
            model_name='printingservice',
            name='rate_volumetric',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ставка за кв.м (объёмные)'),
        ),
        migrations.AddField(
            model_name='servicerecipe',
            name='applies_to',
            field=models.CharField(choices=[('ALL', 'Всегда'), ('FLAT', 'Плоские буквы'), ('VOLUMETRIC', 'Объёмные буквы')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerecipe',
            name='consumption_mode',
            field=models.CharField(choices=[('PER_SQM', 'На кв.м'), ('FIXED', 'Фикс. на заказ')], default='PER_SQM', max_length=10),
        ),
        migrations.AlterField(
            model_name='printingservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Для установки/прочего — фикс. цена за заказ', max_digits=12, verbose_name='фиксированная стоимость'),
        ),
        migrations.AlterField(
            model_name='printingservice',
            name='cardboard_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='printingservice',
            name='paper_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicerecipe',
            name='consumption_per_unit',
            field=models.DecimalField(decimal_places=3, help_text='На кв.м: расход на 1 кв.м; Фикс: расход на заказ', max_digits=12, verbose_name='норма расхода'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerecipe',
            unique_together={('service', 'material', 'applies_to')},
        ),
    ]
