# Generated by Django 6.0.6 on 2026-08-10 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingservice',
            name='machine',
            field=models.CharField(blank=True, choices=[('CNC', 'ЧПУ'), ('LASER', 'Лазер')], default='', help_text='Для резки: на каком станке. По нему группируется отчёт', max_length=10, verbose_name='станок'),
        ),
        migrations.AddField(
            model_name='printingservice',
            name='rate_per_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ставка станка. 0 — берётся ставка материала', max_digits=12, verbose_name='ставка резки, сом/пог.м'),
        ),
    ]
