# Generated by Django 4.2.30 on 2026-06-08 13:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicerecipe_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingservice',
            name='rate_per_piece',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ставка за букву'),
        ),
        migrations.AlterField(
            model_name='printingservice',
            name='kind',
            field=models.CharField(choices=[('CUTTING', 'Резка (по кв.м)'), ('INSTALL_EXTERIOR', 'Наружная установка (за букву)'), ('INSTALL_INTERIOR', 'Внутренняя установка (по кв.м)'), ('INSTALLATION', 'Установка (фикс)'), ('OTHER', 'Прочее (фикс)')], default='CUTTING', max_length=20),
        ),
        migrations.AlterField(
            model_name='printingservice',
            name='rate_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ставка за кв.м (плоские / монтаж)'),
        ),
    ]
