# Generated by Django 4.2.30 on 2026-06-19 14:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_printingservice_rate_per_piece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('4'), help_text='Доля мастера от стоимости работы резки (видна только админу)', max_digits=5, verbose_name='ЗП мастера, % от работы')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки ценообразования',
                'verbose_name_plural': 'настройки ценообразования',
            },
        ),
        migrations.RemoveField(
            model_name='printingservice',
            name='rate_volumetric',
        ),
        migrations.AlterField(
            model_name='printingservice',
            name='kind',
            field=models.CharField(choices=[('CUTTING', 'Резка / работа мастера (по кв.м)'), ('INSTALL_EXTERIOR', 'Наружная установка (за букву)'), ('INSTALL_INTERIOR', 'Внутренняя установка (по кв.м)'), ('INSTALLATION', 'Установка (фикс)'), ('OTHER', 'Прочее (фикс)')], default='CUTTING', max_length=20),
        ),
        migrations.AlterField(
            model_name='printingservice',
            name='rate_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ставка работы за кв.м'),
        ),
        migrations.AlterField(
            model_name='servicerecipe',
            name='applies_to',
            field=models.CharField(choices=[('ALL', 'Всегда')], default='ALL', max_length=20),
        ),
    ]
