# Generated by Django 4.2.30 on 2026-06-19 14:47

from django.db import migrations


def recipes_to_all(apps, schema_editor):
    """Legacy recipes were scoped to FLAT/VOLUMETRIC letters. With the flat/
    volumetric split removed, collapse every recipe to ALL. Delete duplicates
    that would violate the (service, material, applies_to) unique constraint."""
    ServiceRecipe = apps.get_model("services", "ServiceRecipe")
    seen = set()
    for recipe in ServiceRecipe.objects.all().order_by("id"):
        key = (recipe.service_id, recipe.material_id)
        if key in seen:
            recipe.delete()
            continue
        seen.add(key)
        if recipe.applies_to != "ALL":
            recipe.applies_to = "ALL"
            recipe.save(update_fields=["applies_to"])


def ensure_settings(apps, schema_editor):
    PricingSettings = apps.get_model("services", "PricingSettings")
    PricingSettings.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_pricingsettings_and_more'),
    ]

    operations = [
        migrations.RunPython(recipes_to_all, migrations.RunPython.noop),
        migrations.RunPython(ensure_settings, migrations.RunPython.noop),
    ]
