# Generated by Django 6.0.9 on 2026-10-10 11:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='min_line_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Строка услуги дешевле — стоит этот минимум. 0 — выключено', max_digits=12, verbose_name='минимальная сумма строки услуги'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='urgency_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Переключатель «Срочно» в кассе. 0 — выключено', max_digits=5, verbose_name='наценка за срочность, %'),
        ),
        migrations.AddField(
            model_name='printingservice',
            name='min_line_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — общий минимум из настроек; 0 — без минимума', max_digits=12, null=True, verbose_name='минимальная сумма строки'),
        ),
    ]
