# Generated by Django 6.0.9 on 2026-10-10 12:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_pricing_rules'),
        ('warehouse', '0016_inventorylog_roll_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='confirm_line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Строка дороже — касса просит подтвердить. 0 — не спрашивать', max_digits=14, verbose_name='порог подтверждения суммы строки'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='debt_warn_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 — не предупреждать', verbose_name='предупреждать о долге старше, дней'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='min_mode',
            field=models.CharField(choices=[('WORK', 'Работа'), ('PART', 'Деталь (работа + материал)'), ('ORDER', 'Заказ')], default='PART', max_length=10, verbose_name='к чему применять минимум'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='rounding_mode',
            field=models.CharField(choices=[('LINE', 'По строкам'), ('ORDER', 'Итог заказа одной формулой')], default='LINE', max_length=10, verbose_name='округление'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='staff_line_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Складовщик не оформит строку дороже. 0 — без потолка', max_digits=14, verbose_name='потолок суммы строки для складовщика'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='staff_min_price_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Складовщик не впишет цену работы ниже этой доли каталога. 0 — без границы', max_digits=5, verbose_name='нижняя граница ручной цены работы, %'),
        ),
        migrations.AddField(
            model_name='printingservice',
            name='negotiable_price',
            field=models.BooleanField(default=False, help_text='Цену за единицу вписывают в кассе; складовщик — тоже', verbose_name='цена по договорённости'),
        ),
        migrations.AlterField(
            model_name='servicerecipe',
            name='consumption_mode',
            field=models.CharField(choices=[('PER_SQM', 'На кв.м'), ('FIXED', 'Фикс. на заказ'), ('PER_PM', 'На пог.м реза')], default='PER_SQM', max_length=10),
        ),
        migrations.CreateModel(
            name='ThicknessCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CUTTING', 'Резка / работа мастера (по кв.м)'), ('INSTALL_EXTERIOR', 'Наружная установка (за букву)'), ('INSTALL_INTERIOR', 'Внутренняя установка (по кв.м)'), ('INSTALLATION', 'Установка (фикс)'), ('OTHER', 'Прочее (фикс)'), ('ENGRAVING', 'Гравировка (по кв.м)'), ('WASTE', 'Отходы (кв.м / пог.м / шт)')], max_length=20, verbose_name='вид услуги')),
                ('thickness_from', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='толщина от, мм')),
                ('coefficient', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='коэффициент')),
            ],
            options={
                'verbose_name': 'коэффициент по толщине',
                'verbose_name_plural': 'коэффициенты по толщине',
                'ordering': ['kind', 'thickness_from'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'thickness_from'), name='thickness_coef_unique')],
            },
        ),
        migrations.CreateModel(
            name='RateMatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_from', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='толщина от, мм')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ставка')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_matrix', to='warehouse.material')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_matrix', to='services.printingservice')),
            ],
            options={
                'verbose_name': 'ставка матрицы',
                'verbose_name_plural': 'матрица ставок',
                'ordering': ['service', 'thickness_from', 'material'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('service', 'material'), name='rate_matrix_unique_material'), models.UniqueConstraint(condition=models.Q(('thickness_from__isnull', False)), fields=('service', 'thickness_from'), name='rate_matrix_unique_thickness'), models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('thickness_from__isnull', True)), models.Q(('material__isnull', True), ('thickness_from__isnull', False)), _connector='OR'), name='rate_matrix_one_key')],
            },
        ),
    ]
