# Generated by Django 6.0.9 on 2026-10-11 00:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_pricing_modes_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='staff_price_warn_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Складовщик вписал цену работы ниже этой доли каталога — касса предупредит. 0 — не предупреждать', max_digits=5, verbose_name='предупреждать о ручной цене работы ниже, %'),
        ),
    ]
