# Generated by Django 6.0.6 on 2026-08-02 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Физ. лицо'), ('OSOO', 'ОСОО')], default='PHYSICAL', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название компании')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='телефон')),
                ('portal_password', models.CharField(blank=True, default='', max_length=255, verbose_name='пароль портала')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram chat id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='Клиент, который привёл этого клиента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='clients.client', verbose_name='кого привёл')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='', verbose_name='обоснование / причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to='clients.client', verbose_name='клиент')),
                ('new_referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clients.client', verbose_name='новый реферер')),
                ('previous_referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.client', verbose_name='прежний реферер')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто запросил')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто рассмотрел')),
            ],
            options={
                'verbose_name': 'заявка на смену реферера',
                'verbose_name_plural': 'заявки на смену реферера',
                'ordering': ['-created_at'],
            },
        ),
    ]
