# Generated by Django 4.2.30 on 2026-06-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Физ. лицо'), ('OSOO', 'ОСОО')], default='PHYSICAL', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название компании')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='телефон')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram chat id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
