# Generated by Django 4.2.30 on 2026-06-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Клиент, который привёл этого клиента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='clients.client', verbose_name='кого привёл'),
        ),
    ]
