# Generated by Django 6.0.6 on 2026-08-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ИНН'),
        ),
    ]
