# Generated by Django 6.0.6 on 2026-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credentials_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
