# Generated by Django 4.2.30 on 2026-06-09 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_client_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='', verbose_name='обоснование / причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to='clients.client', verbose_name='клиент')),
                ('new_referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clients.client', verbose_name='новый реферер')),
                ('previous_referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.client', verbose_name='прежний реферер')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто запросил')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто рассмотрел')),
            ],
            options={
                'verbose_name': 'заявка на смену реферера',
                'verbose_name_plural': 'заявки на смену реферера',
                'ordering': ['-created_at'],
            },
        ),
    ]
