# Generated by Django 4.2.30 on 2026-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_referralchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='portal_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='пароль портала'),
        ),
    ]
