# Generated by Django 6.0.9 on 2026-10-10 11:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_credentials_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Подставляется в кассе автоматически. 0 — без скидки', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='скидка, %'),
        ),
    ]
