# Generated by Django 6.0.9 on 2026-10-10 12:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_discount_percent'),
        ('sales', '0016_pricing_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Для клиентов без своего лимита. Пусто — лимита нет', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='общий лимит долга, сом')),
                ('storekeeper_takes_debt', models.BooleanField(default=True, verbose_name='складовщик принимает оплату долга')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки клиентов',
                'verbose_name_plural': 'настройки клиентов',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — действует общий лимит из настроек клиентов', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='лимит долга, сом'),
        ),
        migrations.CreateModel(
            name='ClientAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='не зачтено')),
                ('method', models.CharField(choices=[('CASH', 'Наличные'), ('MBANK', 'MBank'), ('DEMIRBANK', 'DemirBank')], default='CASH', max_length=20, verbose_name='способ')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='отменён')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'аванс клиента',
                'verbose_name_plural': 'авансы клиентов',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('CHANGE', 'Сдача прошлых заказов'), ('ADVANCE', 'Аванс')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('used_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата зачёта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offsets', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.receipt')),
                ('advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='clients.clientadvance')),
            ],
            options={
                'verbose_name': 'зачёт',
                'verbose_name_plural': 'зачёты',
                'ordering': ['used_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='начислено')),
                ('accrued_on', models.DateField(verbose_name='дата начисления')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='выплачено')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='дата выплаты')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.receipt')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_as_referred', to='clients.client')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rows', to='clients.client')),
            ],
            options={
                'verbose_name': 'начисление бонуса',
                'verbose_name_plural': 'начисления бонусов',
                'ordering': ['-accrued_on', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('referred',), name='referral_bonus_one_active_per_referred')],
            },
        ),
    ]
