# Generated by Django 6.0.6 on 2026-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_portal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='login_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='login_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
