# Generated by Django 6.0.6 on 2026-07-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_login_code_client_login_code_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='login_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login_code_expires_at',
        ),
    ]
