# Generated by Django 6.0.9 on 2026-10-10 15:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_credit_limit_settings_advances_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientadvance',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name='входящий остаток'),
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEBT', 'Долг клиента'), ('ADVANCE', 'Аванс клиента')], max_length=10, verbose_name='вид')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('remaining', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Для долга — сколько ещё должны; у аванса — 0 (остаток в самом авансе)', max_digits=14, verbose_name='не оплачено')),
                ('as_of', models.DateField(verbose_name='дата переезда')),
                ('as_of_at', models.DateTimeField(editable=False, verbose_name='момент переезда')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('batch', models.CharField(blank=True, max_length=40, verbose_name='партия загрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='отменён')),
                ('advance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening', to='clients.clientadvance', verbose_name='аванс')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'входящий остаток клиента',
                'verbose_name_plural': 'входящие остатки клиентов',
                'ordering': ['as_of', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpeningDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('method', models.CharField(choices=[('CASH', 'Наличные'), ('MBANK', 'MBank'), ('DEMIRBANK', 'DemirBank'), ('WRITE_OFF', 'Списание долга')], default='CASH', max_length=20, verbose_name='способ')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата оплаты')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('cash_entry_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expense_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.openingbalance')),
            ],
            options={
                'verbose_name': 'оплата входящего долга',
                'verbose_name_plural': 'оплаты входящего долга',
                'ordering': ['paid_on', 'id'],
            },
        ),
    ]
