# Generated by Django 6.0.9 on 2026-10-10 15:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_opening_balances'),
        # Нужны только модели PrintingService и Material — берём уже
        # выложенные миграции, а не свежие соседей по волне.
        ('services', '0006_pricing_rules'),
        ('warehouse', '0016_inventorylog_roll_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_mode', models.CharField(blank=True, choices=[('SQM', 'За кв.м'), ('PIECE', 'За лист / штуку'), ('METER', 'За пог.м')], max_length=10, verbose_name='единица материала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='цена, сом')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clients.client')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.material')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='services.printingservice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'договорная цена клиента',
                'verbose_name_plural': 'договорные цены клиентов',
                'ordering': ['client_id', 'service_id', 'material_id', 'sale_mode'],
                'constraints': [models.UniqueConstraint(fields=('client', 'service', 'material', 'sale_mode'), name='client_price_unique')],
            },
        ),
    ]
