# Generated by Django 6.0.9 on 2026-10-10 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='openingdebtpayment',
            name='cancel_cash_entry_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openingdebtpayment',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='причина отмены'),
        ),
        migrations.AddField(
            model_name='openingdebtpayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отменена'),
        ),
        migrations.AddField(
            model_name='openingdebtpayment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
