# Generated by Django 6.0.6 on 2026-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('STOREKEEPER', 'Складовщик'), ('ACCOUNTANT', 'Бухгалтер')], default='STOREKEEPER', max_length=20, verbose_name='роль'),
        ),
    ]
