# Generated by Django 6.0.6 on 2026-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credentials_version',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='версия учётных данных'),
        ),
    ]
