# Generated by Django 6.0.9 on 2026-10-10 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_credentials_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='должность')),
                ('default_machine', models.CharField(blank=True, choices=[('CNC', 'ЧПУ'), ('LASER', 'Лазер')], default='', help_text='Выработка станка идёт этому сотруднику, если он на станке один.', max_length=10, verbose_name='станок по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='работает')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='Заказы, оформленные под этим логином, считаются его выработкой.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='учётная запись')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['-is_active', 'full_name', 'id'],
            },
        ),
    ]
