# Generated by Django 6.0.9 on 2026-10-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_report_date_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='тип'),
        ),
    ]
