# Generated by Django 4.2.30 on 2026-06-05 18:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('CASH', 'Наличные'), ('ONLINE', 'Онлайн-оплата')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAID', 'Оплачено'), ('REFUNDED', 'Возвращено'), ('PARTIALLY_REFUNDED', 'Частичный возврат')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('COMPLETED', 'Совершён'), ('CANCELLED', 'Отменён/Возвращён')], default='COMPLETED', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='итоговая стоимость')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='сумма возврата')),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('payment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, help_text='Складовщик, оформивший чек', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='clients.client')),
            ],
            options={
                'verbose_name': 'чек',
                'verbose_name_plural': 'чеки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MATERIAL', 'Продажа материала'), ('SERVICE', 'Оказание услуги')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='количество')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='цена за единицу на момент продажи')),
                ('is_returned', models.BooleanField(default=False, verbose_name='возвращено')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='warehouse.material')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.receipt')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='services.printingservice')),
            ],
            options={
                'verbose_name': 'позиция чека',
                'verbose_name_plural': 'позиции чека',
            },
        ),
    ]
