# Generated by Django 6.0.6 on 2026-08-02 20:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='номер заказа')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='наименование заказа')),
                ('payment_method', models.CharField(choices=[('CASH', 'Наличные'), ('MBANK', 'MBank'), ('DEMIRBANK', 'DemirBank'), ('ONLINE', 'Онлайн-оплата')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAID', 'Оплачено'), ('REFUNDED', 'Возвращено'), ('PARTIALLY_REFUNDED', 'Частичный возврат')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('COMPLETED', 'Совершён'), ('CANCELLED', 'Отменён/Возвращён')], default='COMPLETED', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('PROCESSING', 'Готовится'), ('READY', 'Готово к выдаче'), ('ISSUED', 'Выдан')], default='PROCESSING', help_text='Готовится → Готово к выдаче → Выдан (для заказов с услугами)', max_length=20, verbose_name='статус выполнения')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='итоговая стоимость')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='сумма возврата')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='оплачено (предоплата)')),
                ('stock_deducted', models.BooleanField(default=False, help_text='Материал уже списан со склада — для корректного возврата.', verbose_name='склад списан')),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('payment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, help_text='Складовщик, оформивший чек', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='clients.client')),
            ],
            options={
                'verbose_name': 'чек',
                'verbose_name_plural': 'чеки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MATERIAL', 'Продажа материала'), ('SERVICE', 'Оказание услуги')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='количество')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='цена за единицу на момент продажи')),
                ('sale_mode', models.CharField(blank=True, choices=[('SQM', 'По площади / кв.м'), ('PIECE', 'Целиком (лист/рулон)')], default='SQM', max_length=10)),
                ('cost_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='себестоимость строки')),
                ('letter_type', models.CharField(blank=True, max_length=20)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_returned', models.BooleanField(default=False, verbose_name='возвращено')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='warehouse.material')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.receipt')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='services.printingservice')),
            ],
            options={
                'verbose_name': 'позиция чека',
                'verbose_name_plural': 'позиции чека',
            },
        ),
    ]
