# Generated by Django 4.2.30 on 2026-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='fulfillment_status',
            field=models.CharField(choices=[('PROCESSING', 'Готовится'), ('READY', 'Готово к выдаче'), ('ISSUED', 'Выдан')], default='PROCESSING', help_text='Готовится → Готово к выдаче → Выдан (для заказов с услугами)', max_length=20, verbose_name='статус выполнения'),
        ),
    ]
