# Generated by Django 6.0.6 on 2026-08-02 21:06
#
# Вторая «initial» у sales — не накопленная история, а как Django разрывает
# круг: warehouse.InventoryLog ссылается на sales.Receipt (журнал знает, по
# какому чеку ушёл материал), а sales.TransactionItem — на warehouse.Material.
# Кто-то должен создаться без внешних ключей и получить их следом; Django
# выбрал sales. Пересобирается вместе с остальными initial, отдельно не трогать.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('services', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='warehouse.material'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.receipt'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='services.printingservice'),
        ),
    ]
