# Generated by Django 4.2.30 on 2026-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_receipt_fulfillment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='letter_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
