# Generated by Django 6.0.6 on 2026-08-08 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата заказа'),
        ),
    ]
