# Generated by Django 4.2.30 on 2026-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_transactionitem_length_transactionitem_letter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='sale_mode',
            field=models.CharField(blank=True, choices=[('SQM', 'По площади / кв.м'), ('PIECE', 'Целиком (лист/рулон)')], default='SQM', max_length=10),
        ),
    ]
