# Generated by Django 6.0.6 on 2026-08-10 09:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_receipt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Переплата, которую ещё не вернули на руки', max_digits=14, verbose_name='сдача клиенту'),
        ),
    ]
