# Generated by Django 4.2.30 on 2026-06-19 15:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_transactionitem_sale_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='количество'),
        ),
    ]
