# Generated by Django 4.2.30 on 2026-06-27 11:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_transactionitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='оплачено (предоплата)'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Материал уже списан со склада — для корректного возврата.', verbose_name='склад списан'),
        ),
    ]
