# Generated by Django 6.0.6 on 2026-08-17 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_receipt_change_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='change_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Часть заказа, закрытая сдачей с прошлых заказов клиента', max_digits=14, verbose_name='зачтено сдачей'),
        ),
    ]
