# Generated by Django 4.2.30 on 2026-07-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_receipt_amount_paid_receipt_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='номер заказа'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('MBANK', 'MBank'), ('DEMIRBANK', 'DemirBank'), ('ONLINE', 'Онлайн-оплата')], default='CASH', max_length=20),
        ),
    ]
