# Generated by Django 6.0.6 on 2026-08-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_receipt_change_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='sale_mode',
            field=models.CharField(blank=True, choices=[('SQM', 'По площади / кв.м'), ('PIECE', 'Целиком (лист/рулон)'), ('METER', 'По длине / пог.м')], default='SQM', max_length=10),
        ),
    ]
