# Generated by Django 6.0.6 on 2026-08-18 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_transactionitem_sale_mode'),
        ('warehouse', '0007_roll_declared_length_alter_material_roll_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to='warehouse.roll', verbose_name='рулон'),
        ),
    ]
