# Generated by Django 6.0.6 on 2026-07-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_backfill_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='наименование заказа'),
        ),
    ]
