# Generated by Django 6.0.6 on 2026-08-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_transactionitem_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='used_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сколько ширины ушло клиенту. Остальное — обрезок цеха', max_digits=8, null=True, verbose_name='ширина изделия, м'),
        ),
    ]
