# Generated by Django 6.0.6 on 2026-09-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_transactionitem_own_material_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата возврата'),
        ),
    ]
