# Generated by Django 6.0.6 on 2026-10-10 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_revenue_recognized_backfill'),
        ('warehouse', '0014_roll_supplier_debt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=100)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItemLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='взято, кв.м (шт)')),
                ('metres', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='взято, пог.м')),
            ],
            options={
                'verbose_name': 'партия строки чека',
                'verbose_name_plural': 'партии строк чека',
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['created_at'], name='receipt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['revenue_recognized_at'], name='receipt_recognized_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment_status'], name='receipt_paystatus_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['returned_at'], name='item_returned_at_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['receipt', 'is_returned'], name='item_receipt_ret_idx'),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='sales.receipt'),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionitemlot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_uses', to='sales.transactionitem'),
        ),
        migrations.AddField(
            model_name='transactionitemlot',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_uses', to='warehouse.roll', verbose_name='партия'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('user', 'endpoint', 'key'), name='idempotency_unique_key'),
        ),
    ]
