# Generated by Django 6.0.9 on 2026-10-10 11:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_idempotency_item_lots_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='скидка, %'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='срочно'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='urgency_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='наценка за срочность, %'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='catalog_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='цена до правил'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='скидка, %'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='минимум строки'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='min_applied',
            field=models.BooleanField(default=False, verbose_name='применён минимум'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='urgency_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='срочность, %'),
        ),
    ]
