# Generated by Django 6.0.9 on 2026-10-10 12:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_discount_percent'),
        ('sales', '0016_pricing_rules'),
        ('warehouse', '0016_inventorylog_roll_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expense_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='имя покупателя'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_warranty',
            field=models.BooleanField(default=False, verbose_name='гарантия / переделка'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='warranty_culprit',
            field=models.CharField(blank=True, help_text='Кто допустил брак. Текстом: справочника сотрудников в продажах нет', max_length=120, verbose_name='виновник'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='warranty_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_orders', to='sales.receipt', verbose_name='исходный заказ'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='warranty_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='причина переделки'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='issued_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='выдано'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='parts_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='деталей, шт'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='passes',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='проходов'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='price_is_manual',
            field=models.BooleanField(default=False, verbose_name='цена вписана вручную'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='thickness_coef',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='коэффициент толщины'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='work_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.material', verbose_name='материал работы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('MBANK', 'MBank'), ('DEMIRBANK', 'DemirBank'), ('ONLINE', 'Онлайн-оплата'), ('CHANGE', 'Зачёт сдачи'), ('WRITE_OFF', 'Списание долга')], default='CASH', max_length=20, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fulfillment_status',
            field=models.CharField(choices=[('PROCESSING', 'Готовится'), ('READY', 'Готово к выдаче'), ('PARTIALLY_ISSUED', 'Выдан частично'), ('ISSUED', 'Выдан')], default='PROCESSING', help_text='Готовится → Готово к выдаче → Выдан (для заказов с услугами)', max_length=20, verbose_name='статус выполнения'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='номер КП')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='кому')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='наименование')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('status', models.CharField(choices=[('ACTIVE', 'Действует'), ('ORDERED', 'Оформлен заказ'), ('CANCELLED', 'Отменено')], default='ACTIVE', max_length=12)),
                ('cart', models.JSONField(default=list, verbose_name='позиции корзины')),
                ('lines', models.JSONField(default=list, verbose_name='посчитанные строки')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='итого')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='срочно')),
                ('urgency_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotes', to='sales.receipt', verbose_name='заказ из КП')),
            ],
            options={
                'verbose_name': 'коммерческое предложение',
                'verbose_name_plural': 'коммерческие предложения',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
