# Generated by Django 6.0.9 on 2026-10-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee'),
        ('sales', '0017_calc_quotes_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_lines', to='accounts.employee', verbose_name='исполнитель'),
        ),
    ]
