# Generated by Django 6.0.9 on 2026-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_transactionitem_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='client_price',
            field=models.BooleanField(default=False, verbose_name='договорная цена клиента'),
        ),
    ]
