# Generated by Django 6.0.9 on 2026-10-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_transactionitem_client_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='roll_area',
            field=models.BooleanField(default=False, verbose_name='рулон по площади изделия'),
        ),
    ]
