# Generated by Django 6.0.9 on 2026-10-10 17:39
#
# Перепроверка 10.10 (RU-N3): выдача по позициям в ДЕТАЛЯХ. Поле аддитивное;
# уже выданное переносится из `issued_qty` (выдано целиком — все детали,
# частично — ближайшее целое). Откат — просто удаление поля.
from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def backfill(apps, schema_editor):
    TransactionItem = apps.get_model("sales", "TransactionItem")
    rows = TransactionItem.objects.filter(parts_count__gt=1, issued_qty__gt=0)
    for item in rows.iterator():
        if item.quantity <= 0:
            continue
        if item.issued_qty >= item.quantity:
            parts = item.parts_count
        else:
            parts = int(
                (item.issued_qty * item.parts_count / item.quantity).quantize(
                    Decimal("1"), rounding=ROUND_HALF_UP
                )
            )
            parts = max(0, min(parts, item.parts_count))
        if parts:
            TransactionItem.objects.filter(pk=item.pk).update(issued_parts=parts)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_transactionitem_roll_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='issued_parts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='выдано деталей'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
