# Generated by Django 6.0.9 on 2026-10-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_transactionitem_issued_parts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionitem',
            options={'ordering': ['id'], 'verbose_name': 'позиция чека', 'verbose_name_plural': 'позиции чека'},
        ),
    ]
