# Generated by Django 6.0.9 on 2026-10-11 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_transactionitem_ordering'),
        ('warehouse', '0027_leftover'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='leftover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_items', to='warehouse.leftover', verbose_name='остаток с полки'),
        ),
    ]
